### ISSUE TITLE
Cache namespace not respected

### ISSUE THREAD

**Issue by nsollecito** [andreacfm/Redis-Cache-Extension#6]
Multiple caches w/different namespace defined do not get carried across requests from Railo. Whatever the last cache name set up in Railo was, that seems to be the namespace used. 

For now, the workaround for this issue is to just leave the default namespace and do not change it for any additional cachename created.

**Comment by andreacfm** [comment]
I hope this https://github.com/andreacfm/Redis-Cache-Extension/commit/9ba6404d554c537ead9983b4f8b25d3f0c13b041 solves your issue
